import = ["~/.config/alacritty/themes/theme.toml"]

[env]
TERM = "alacritty"

#[shell]
#program = "/bin/bash"

[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "HurmitNerdFontMono", style = "Regular" }
bold = { family = "HurmitNerdFontMono", style = "Bold" }
italic = { family = "HurmitNerdFontMono", style = "Italic" }
bold_italic = { family = "HurmitNerdFontMono", style = "BoldItalic" }
size = 12

[cursor]
style = { shape = "underline", blinking = "always" }
unfocused_hollow = false

[mouse]
hide_when_typing = true
